import type { Locale } from "./index.ts"

/** 英文文案 */
export const en: Locale = {
  // Root README
  rootTitle: "📚 My Stories",
  rootStats: (count, wordCount, date) => `✍️ **${count}** stories · **${wordCount}** · Updated: ${date}`,
  rootWelcome: "Welcome to my writing repository.",
  tocLabel: "📑 Table of Contents",
  tocStoryList: "📖 Story List",
  tocHowToAdd: "📝 How to Add a Story",
  tocArchitecture: "🔧 Architecture",
  tocSponsor: "☕ Support",
  tocLicense: "⚖️ License",
  storyListTitle: "📖 Story List",
  storyListHeader: "| # | Story | Type | Words | Status | Summary |\n|---|-------|------|-------|--------|---------|",
  storyListHint: "> 💡 Click a story title to read. Text is in each folder's `text.md`.",
  independentStoriesTitle: "📌 Standalone Stories",
  howToAddTitle: "📝 How to Add a Story",
  howToAddDesc: "Want to add a new story? See [docs/add-story.md](docs/add-story.md) — just 3 steps:",
  howToAddStep1: "1. Create folder `NN-story-name/`",
  howToAddStep2: "2. Write `config.json`",
  howToAddStep3: "3. Run `pnpm build`",
  architectureTitle: "🔧 Architecture",
  architectureDesc: "Learn about the build system and module design in [docs/architecture.md](docs/architecture.md).",
  sponsorTitle: "☕ Support",
  sponsorSummary: "If you like my work, feel free to buy me a coffee.",
  licenseTitle: "⚖️ License",
  licenseOriginal:
    "Original stories are licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).",
  licenseFanfic: "Fan fiction belongs to original creators. Commercial use prohibited.",
  autoGenerated: "This README was auto-generated. Do not edit manually.",

  // Story README
  backToStoryList: "← Back to Story List",
  seriesLabel: "Series",
  relatedStoriesTitle: "🔗 Related Stories",
  basicInfoTitle: "📝 Basic Info",
  typeLabel: "Type",
  wordCountLabel: "Word Count",
  statusLabel: "Status",
  createDateLabel: "First Published",
  summaryTitle: "📖 Summary",
  readingGuideTitle: "📚 Reading Guide",
  textFileLabel: "Text File",
  chaptersTitle: "📑 Chapters",
  licenseOriginalText:
    "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). You are free to share, non-commercially; derivatives must use the same license.",
  licenseFanficText: (work, author) =>
    `This is a fan work based on ${work} (by ${author}). Original characters and world rights belong to the original creators.`,
  licenseFanficNote:
    "Original plot and dialogue are covered by CC BY-NC-SA 4.0. **Commercial use is strictly prohibited.**",

  // Type/status mapping
  type: {
    original: "Original",
    fanfic: "Fan Fiction",
  },
  status: {
    completed: "Completed",
    ongoing: "Ongoing",
  },

  // Word count formats
  wordCountFormat: {
    thousand: (n) => `~${n}K words`,
    char: (n) => `~${n} words`,
    empty: "Word count TBD",
  },
  totalWordCountFormat: {
    tenThousand: (n) => `~${(n / 1000).toFixed(1)}K words`,
    thousand: (n) => `~${Math.round(n / 1000)}K words`,
    char: (n) => `~${n} words`,
  },

  // CLI output
  scanning: "🔍 Scanning story folders...",
  buildSuccess: (count) =>
    `✅ Build complete! Generated ${count} story READMEs + 1 root README (${count} stories total)`,
  buildFail: "❌ Build failed with the following errors:",
  validateOnly: (count) => `✅ Validation passed. ${count} story configs are valid`,
  duplicateNumberWarning: (num) => `⚠️ Duplicate number "${num}" detected, sorting may be unexpected`,
  renameWarning: (oldName, newName) => `⚠️ Detected folder rename: ${oldName} → ${newName}`,
  renameWarningHint: () =>
    `   Please do not rename existing story folders to keep links stable. To adjust order, use series / seriesOrder in config.json.`,
  generatingReadmes: "📝 Generating story READMEs...",
  generatingRoot: "  ✅ README.md",
  missingConfig: (folder) => `❌ ${folder}: missing config.json`,
  configParseError: (folder, msg) => `❌ ${folder}: config.json parse failed - ${msg}`,
  autoWordCount: (folder, wc, saved) =>
    `📊 ${folder}: auto word count = ${wc}${saved ? "" : " (not saved, use --save-counts to persist)"}`,
  generatedText: (folder) => `📄 ${folder}: text.md generated (merged chapters)`,
  mergedWarning: (folder) => `⚠️ ${folder}: text.md not found, merged from chapter-*.md`,
  storyReadmeDone: (folder) => `  ✅ ${folder}/README.md`,
  noSummary: "No summary",
  skippedExport: (n) => `  ⚠️ ${n} stories skipped`,

  // story new command
  newMissingTitle: `Please specify a story title!
  Usage: story new "Title" [--type=original|fanfic] [--author="Work"] [--creator="Author"] [--lang=zh|en]

  Examples:
    story new "My First Story"
    story new "Fan Work" --type=fanfic --author="Original Work" --creator="Author" --lang=en`,
  newTypeInvalid: (choices, got) => `--type must be ${choices.map((v) => `"${v}"`).join(" or ")}, got "${got}"`,
  newFanficRequiresAuthor: `Fan fiction requires --author="Original Work Name"`,
  newFanficRequiresCreator: `Fan fiction requires --creator="Original Author"`,
  newFolderExists: (folder) => `Folder already exists: ${folder}`,
  newConfigInvalid: (issues) => `Config validation failed: ${issues}`,
  newCreated: (folderName, type) => `✅ Created story: ${folderName}/
   ├── config.json (type: ${type})
   └── text.md`,
  newNextSteps: (folderName) => `
Next steps:
  1. Edit ${folderName}/config.json
  2. Write in ${folderName}/text.md
  3. Run: story build
`,

  // Watch mode
  watchStart: "Watch mode started. Auto-rebuilding on file changes...",
  watchRebuild: (trigger) => `Change detected (${trigger}), rebuilding...`,
  watchDone: (count) => `✅ Rebuild complete! ${count} stories`,
  watchHint: "Waiting for file changes... (Ctrl+C to exit)",
  watchExit: "Watch mode exited",

  // EPUB export
  epubExporting: "📚 Exporting EPUB...",
  epubMissingConfig: (folder) => `❌ ${folder}: missing config.json`,
  epubConfigParse: (folder, msg) => `❌ ${folder}: config.json parse failed - ${msg}`,
  epubInvalidConfig: (folder) => `❌ ${folder}: config validation failed`,
  epubEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,
  epubImageMissing: (src) => `⚠️ Image not found: ${src}`,
  epubImageReadFailed: (src, msg) => `⚠️ Failed to read image: ${src} - ${msg}`,
  epubExportSuccess: (folder, output, sizeKB, imgCount) => `✅ ${folder} → ${output} (${sizeKB} KB${imgCount})`,
  epubExportFailed: (folder, msg) => `❌ ${folder}: export failed - ${msg}`,
  epubStats: (success, failed) => `📊 Export complete: ${success} success, ${failed} failed`,
  epubOutputDir: (output) => `📁 Output: ${output}`,
  epubNoArgsError: `Please specify a story title or use --all!\n  Usage:\n    story epub "Title"       # Export one story\n    story epub --all           # Export all stories`,
  epubNotFound: (title) => `No story folder matching "${title}"`,
  epubCoverMissing: (p) => `⚠️ Cover image not found: ${p}`,
  epubSvgUnsafe: (p) => `⚠️ Cover SVG contains dangerous content (scripts/event handlers), skipped: ${p}`,
  epubCoverReadFailed: (p, msg) => `⚠️ Failed to read cover image: ${p} - ${msg}`,
  epubCssMissing: (p) => `⚠️ Custom stylesheet not found: ${p}, falling back to built-in style`,
  epubLicenseOriginal:
    "This work is licensed under CC BY-NC-SA 4.0. You are free to share, non-commercially; derivatives must use the same license.",
  epubLicenseFanfic: (work, author) =>
    `This is a fan work based on ${work} (by ${author}). Original characters and world rights belong to the original creators. Commercial use is strictly prohibited.`,

  // HTML export
  htmlExporting: "🌐 Exporting HTML site...",
  htmlExportSuccess: (count, output) => `✅ HTML export complete: ${count} stories → ${output}/index.html`,
  htmlInvalidConfig: (folder) => `❌ ${folder}: config validation failed, skipped`,
  htmlEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

  // Plain text export
  txtExporting: "📄 Exporting plain text...",
  txtExportSuccess: (count, output) => `✅ Plain text export complete: ${count} stories → ${output}/`,
  txtInvalidConfig: (folder) => `❌ ${folder}: config validation failed, skipped`,
  txtEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

  // JSON export
  jsonExporting: "🔗 Exporting structured JSON...",
  jsonExportSuccess: (count, output) => `✅ JSON export complete: ${count} stories → ${output}`,
  jsonEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

  // Markdown export (merged single file)
  mdExporting: "📄 Exporting merged Markdown...",
  mdExportSuccess: (count, output) => `✅ Markdown export complete: ${count} stories → ${output}/`,
  mdEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

  // Embeddings export
  embeddingsExporting: "🧠 Exporting text chunks (embeddings)...",
  embeddingsExportSuccess: (chunks, output) => `✅ Embeddings export complete: ${chunks} chunks → ${output}`,
  embeddingsEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

  // Demo mode
  demoGenerating: "🎬 Generating demo story repository...",
  demoDone: "✅ Demo story repository created!",
  demoExplain: (count) => `Created ${count} demo stories. You can:

  1. Edit any story's text.md to start writing
  2. Run \`story build\` to generate READMEs (already done)
  3. Run \`story epub "Starlight Dreams"\` to export EPUB
  4. Run \`story export html\` to export a static site

  This directory is now a fully functional story repository — ready to commit to Git!`,

  // Stats
  statsScanning: "📊 Collecting writing statistics...",
  statsStoryCount: (count, completed, ongoing) => `📚 Stories: ${count} (${completed} completed / ${ongoing} ongoing)`,
  statsTotalWords: (words, chapters) => `📝 Total words: ${words} (${chapters} chapters)`,
  statsSeries: (name, count, completion) => `📈 Series "${name}": ${count} stories → ${completion}`,
  statsStandalone: (count) => `📌 Standalone stories: ${count}`,
  statsActivity: (thisMonth, lastMonth) => `🔥 Writing activity: this month ${thisMonth} (last month ${lastMonth})`,
  statsNoGit: "⚠️ Not a git repository, cannot compute writing activity",
  statsHealthTitle: (count) => `⚠️ Health check: ${count} warnings`,
  statsStaleWordCount: (folder, config, actual) =>
    `    [Stale word count] ${folder}: config=${config}, actual=${actual}`,
  statsHealthy: "✅ Health check: all good",
  statsThisMonth: "this month",
  statsLastMonth: "last month",

  // JSON import
  importJsonReading: "📥 Importing stories from JSON...",
  importJsonFileNotFound: (p) => `File not found: ${p}`,
  importJsonEmptyInput: "stdin is empty. Use --file to specify a file or pipe JSON through stdin",
  importJsonUsage: `Usage:
story import json --file=stories.json    # Import from file
story import json < stories.json          # Import from stdin
story import json --file=stories.json --output=my-stories/  # Specify output directory`,
  importJsonReadFailed: (msg) => `Failed to read input - ${msg}`,
  importJsonParseError: (msg) => `JSON parse failed - ${msg}`,
  importJsonInvalidFormat: 'Invalid JSON format: root structure should be { "stories": [...] }',
  importJsonMissingTitle: (i) => `Story #${i} is missing the title field, skipped`,
  importJsonDone: (success, failed) => `📥 Import complete: ${success} success, ${failed} failed`,
  importJsonOutputDir: (dir) => `Output directory: ${dir}`,
  importJsonNextStep: "Run `story build` to generate READMEs",
  importJsonValidationFailed: (title, issues) => `  ⚠️ ${title}: ${issues}`,
  importJsonTitleExists: (title) => `  ⚠️ ${title}: a story with the same title already exists, skipped`,
  importJsonDirExists: (folder) => `  ⚠️ ${folder}: directory already exists, skipped`,

  // Encoding detection
  encodingGbkWarning: (filePath) => `⚠️ ${filePath} may use GBK/GB2312 encoding. Please re-save it as UTF-8 and re-run.`,
  encodingUnknownWarning: (filePath) => `⚠️ ${filePath} is not valid UTF-8. Please convert it to UTF-8 and re-run.`,

  // Compliance check (story validate)
  complianceTitle: "📐 Checking repository compliance...",
  compliancePass: (count) => `✅ Compliance check passed: ${count} stories conform to the Story-Repo spec`,
  complianceFail: (errorCount, warningCount) =>
    `❌ Compliance check failed: ${errorCount} errors, ${warningCount} warnings`,
  complianceInvalidFolderName: (folder) => `Folder name does not match "NN-name" (at least 2 digits): ${folder}`,
  complianceDuplicateNumber: (num, existing, folder) => `Duplicate number "${num}": ${existing} and ${folder}`,
  complianceMissingConfig: (folder) => `${folder}: missing config.json`,
  complianceInvalidConfig: (folder) => `${folder}: config.json is invalid (unparseable or fails schema)`,
  complianceMissingContent: (folder) => `${folder}: missing content (need text.md or chapter-*.md)`,
  complianceEncoding: (folder, file) => `${folder}/${file} is possibly not UTF-8 encoded`,

  // story link
  linkUsage: `Usage: story link <sourceFolder> <targetFolder>  |  story link --remove=<target> <source>  |  story link --list [source]`,
  linkNotFound: (folder) => `Story folder not found: ${folder}`,
  linkMissingConfig: (folder) => `${folder}: missing config.json`,
  linkParseError: (folder) => `${folder}: failed to parse config.json`,
  linkList: (source, links) => `${source}: ${links}`,
  linkNone: "no links",
  linkNotPresent: (source, target) => `${source} is not linked to ${target}`,
  linkRemoved: (source, target) => `Removed ${source} → ${target}`,
  linkSelf: (source) => `Cannot link ${source} to itself`,
  linkAlreadyPresent: (source, target) => `${source} already linked to ${target} (idempotent)`,
  linkAdded: (source, target) => `Added ${source} → ${target}`,

  // build link suggestions
  linkSuggestionTitle: "🔗 Possible related stories detected (not auto-written; confirm manually):",
  linkSuggestionLine: (source, target, shared) => `  - ${source} ↔ ${target} (${shared} shared keywords)`,
  linkSuggestionHint: () => `    To confirm, run: story link "<source>" "<target>"`,
}
