/**
 * 国际化模块入口
 * 提供中英文文案映射与格式化函数
 *
 * 结构说明：
 * - 本文件：Locale 接口定义 + 合并语言文件 + 导出函数
 * - zh.ts：中文文案
 * - en.ts：英文文案
 */

/**
 * 国际化模块
 * 提供中英文文案映射
 */

import type { Language, StoryStatus, StoryType } from "../core/types.ts"

/** 单个语言的完整文案结构 */
export interface Locale {
  // 根 README
  rootTitle: string
  rootStats: (count: number, wordCount: string, date: string) => string
  rootWelcome: string
  tocLabel: string
  tocStoryList: string
  tocHowToAdd: string
  tocArchitecture: string
  tocSponsor: string
  tocLicense: string
  storyListTitle: string
  storyListHeader: string
  storyListHint: string
  /** 独立故事区块标题（根 README 系列分组展示用） */
  independentStoriesTitle: string
  howToAddTitle: string
  howToAddDesc: string
  howToAddStep1: string
  howToAddStep2: string
  howToAddStep3: string
  architectureTitle: string
  architectureDesc: string
  sponsorTitle: string
  sponsorSummary: string
  licenseTitle: string
  licenseOriginal: string
  licenseFanfic: string
  autoGenerated: string

  // 故事 README
  backToStoryList: string
  /** 系列标签（故事 README 显示用） */
  seriesLabel: string
  basicInfoTitle: string
  typeLabel: string
  wordCountLabel: string
  statusLabel: string
  createDateLabel: string
  summaryTitle: string
  readingGuideTitle: string
  textFileLabel: string
  chaptersTitle: string
  licenseOriginalText: string
  licenseFanficText: (work: string, author: string) => string
  licenseFanficNote: string

  // 类型/状态映射
  type: Record<StoryType, string>
  status: Record<StoryStatus, string>

  // 字数格式
  wordCountFormat: {
    thousand: (n: number) => string
    char: (n: number) => string
    empty: string
  }
  totalWordCountFormat: {
    tenThousand: (n: number) => string
    thousand: (n: number) => string
    char: (n: number) => string
  }

  // CLI 输出
  scanning: string
  buildSuccess: (count: number) => string
  buildFail: string
  validateOnly: (count: number) => string
  duplicateNumberWarning: (num: string) => string
  /** 文件夹重命名警示（build 时检测到 R 状态） */
  renameWarning: (oldName: string, newName: string) => string
  renameWarningHint: () => string
  generatingReadmes: string
  generatingRoot: string
  missingConfig: (folder: string) => string
  configParseError: (folder: string, msg: string) => string
  autoWordCount: (folder: string, wc: string, saved: boolean) => string
  generatedText: (folder: string) => string
  mergedWarning: (folder: string) => string
  storyReadmeDone: (folder: string) => string
  noSummary: string

  // Watch 模式
  watchStart: string
  watchRebuild: (trigger: string) => string
  watchDone: (count: number) => string
  watchHint: string
  watchExit: string

  // EPUB 导出
  epubExporting: string
  epubMissingConfig: (folder: string) => string
  epubConfigParse: (folder: string, msg: string) => string
  epubInvalidConfig: (folder: string) => string
  epubEmptyContent: (folder: string) => string
  epubImageMissing: (src: string) => string
  epubImageReadFailed: (src: string, msg: string) => string
  epubExportSuccess: (folder: string, output: string, sizeKB: string, imgCount: string) => string
  epubExportFailed: (folder: string, msg: string) => string
  epubStats: (success: number, failed: number) => string
  epubOutputDir: (output: string) => string
  epubNoArgsError: string
  epubNotFound: (title: string) => string
  /** 封面图片不存在 */
  epubCoverMissing: (path: string) => string
  /** 封面 SVG 含危险内容 */
  epubSvgUnsafe: (path: string) => string
  /** 封面图片读取失败 */
  epubCoverReadFailed: (path: string, msg: string) => string

  // HTML 导出
  htmlExporting: string
  htmlExportSuccess: (count: number, output: string) => string
  htmlInvalidConfig: (folder: string) => string
  htmlEmptyContent: (folder: string) => string

  // 纯文本导出
  txtExporting: string
  txtExportSuccess: (count: number, output: string) => string
  txtInvalidConfig: (folder: string) => string
  txtEmptyContent: (folder: string) => string

  // JSON 导出
  jsonExporting: string
  jsonExportSuccess: (count: number, output: string) => string
  jsonEmptyContent: (folder: string) => string

  // Markdown 导出（合并单文件）
  mdExporting: string
  mdExportSuccess: (count: number, output: string) => string
  mdEmptyContent: (folder: string) => string

  // Demo 模式
  /** 正在生成示例仓库 */
  demoGenerating: string
  /** 演示完成提示 */
  demoDone: string
  /** 演示说明 */
  demoExplain: (count: number) => string

  // Stats 创作统计
  /** 正在统计中 */
  statsScanning: string
  /** 故事数量统计 */
  statsStoryCount: (count: number, completed: number, ongoing: number) => string
  /** 总字数统计 */
  statsTotalWords: (words: string, chapters: number) => string
  /** 系列统计 */
  statsSeries: (name: string, count: number, completion: string) => string
  /** 独立故事数 */
  statsStandalone: (count: number) => string
  /** 写作活跃度 */
  statsActivity: (thisMonth: string, lastMonth: string) => string
  /** 无 git 历史 */
  statsNoGit: string
  /** 健康度警告标题 */
  statsHealthTitle: (count: number) => string
  /** 字数过期警告 */
  statsStaleWordCount: (folder: string, config: string, actual: string) => string
  /** 缺少 summary 警告 */
  statsMissingSummary: (folder: string) => string
  /** 无警告 */
  statsHealthy: string
  /** 本月 */
  statsThisMonth: string
  /** 上月 */
  statsLastMonth: string

  // JSON 导入
  /** 正在读取 JSON  */
  importJsonReading: string
  /** 文件不存在 */
  importJsonFileNotFound: (path: string) => string
  /** stdin 输入为空 */
  importJsonEmptyInput: string
  /** 用法提示 */
  importJsonUsage: string
  /** 读取失败 */
  importJsonReadFailed: (msg: string) => string
  /** JSON 解析失败 */
  importJsonParseError: (msg: string) => string
  /** JSON 格式无效 */
  importJsonInvalidFormat: string
  /** 第 N 条缺少标题 */
  importJsonMissingTitle: (index: number) => string
  /** 导入完成统计 */
  importJsonDone: (success: number, failed: number) => string
  /** 输出目录 */
  importJsonOutputDir: (dir: string) => string
  /** 下一步提示 */
  importJsonNextStep: string

  // 编码检测
  /** 检测到 GBK/GB2312 编码警告 */
  encodingGbkWarning: (filePath: string) => string
  /** 检测到未知非 UTF-8 编码警告 */
  encodingUnknownWarning: (filePath: string) => string
}

import { en } from "./en.ts"
import { zh } from "./zh.ts"

/** 所有语言的文案对象 */
export const LOCALES: Record<Language, Locale> = { zh, en }

/**
 * 获取指定语言的文案
 * @param lang 语言代码（zh / en）
 * @returns 文案对象
 */
export function getLocale(lang: string | Language): Locale {
  return LOCALES[lang as Language] || LOCALES.en
}

/**
 * 将类型代码映射为显示文本
 * 优先使用仓库级自定义标签；未配置时回退到内置映射；最后回退到原始代码
 * @param typeCode 类型代码（original / fanfic / 自定义）
 * @param lang 语言
 * @param labels 仓库级自定义标签（可选）
 * @returns 显示文本
 */
export function formatType(typeCode: string, lang: Language, labels?: Record<string, Record<string, string>>): string {
  if (labels?.[typeCode]?.[lang]) return labels[typeCode][lang]
  const locale = getLocale(lang)
  return locale.type[typeCode as StoryType] || typeCode
}

/**
 * 将状态代码映射为显示文本
 * 优先使用仓库级自定义标签；未配置时回退到内置映射；最后回退到原始代码
 * @param statusCode 状态代码（completed / ongoing / 自定义）
 * @param lang 语言
 * @param labels 仓库级自定义标签（可选）
 * @returns 显示文本
 */
export function formatStatus(
  statusCode: string,
  lang: Language,
  labels?: Record<string, Record<string, string>>,
): string {
  if (labels?.[statusCode]?.[lang]) return labels[statusCode][lang]
  const locale = getLocale(lang)
  return locale.status[statusCode as StoryStatus] || statusCode
}

/**
 * 解析故事语言（从 config.json 中读取，默认 zh）
 * @param config 故事配置
 * @returns 语言代码
 */
export function resolveLang(config: { language?: string }): Language {
  return config.language === "en" ? "en" : "zh"
}
