import type { Locale } from "./index.ts"

/** 中文文案 */
export const zh: Locale = {
  // 根 README
  rootTitle: "📚 我的故事集",
  rootStats: (count, wordCount, date) => `✍️ 共 **${count}** 个故事 · **${wordCount}** · 最后更新：${date}`,
  rootWelcome: "欢迎来到我的创作仓库。",
  tocLabel: "📑 目录",
  tocStoryList: "📖 故事列表",
  tocHowToAdd: "📝 如何新增故事",
  tocArchitecture: "🔧 技术架构",
  tocSponsor: "☕ 赞助支持",
  tocLicense: "⚖️ 许可证",
  storyListTitle: "📖 故事列表",
  storyListHeader: "| # | 故事 | 类型 | 字数 | 状态 | 简介 |\n|---|------|------|------|------|------|",
  storyListHint: "> 💡 点击故事标题进入阅读页，正文见各目录下的 `text.md`",
  independentStoriesTitle: "📌 独立故事",
  howToAddTitle: "📝 如何新增故事",
  howToAddDesc: "想添加新故事？请参考 [docs/add-story.md](docs/add-story.md)，只需 3 步即可完成：",
  howToAddStep1: "1. 创建目录 `NN-故事名/`",
  howToAddStep2: "2. 编写 `config.json`",
  howToAddStep3: "3. 运行 `pnpm build`",
  architectureTitle: "🔧 技术架构",
  architectureDesc: "了解本仓库的构建系统与模块设计，请参阅 [docs/architecture.md](docs/architecture.md)。",
  sponsorTitle: "☕ 赞助支持",
  sponsorSummary: "如果你喜欢我的创作，可以请我喝杯咖啡。",
  licenseTitle: "⚖️ 许可证",
  licenseOriginal: "原创故事采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可证。",
  licenseFanfic: "二创故事版权归原作者所有，禁止商用。",
  autoGenerated: "本 README 由脚本自动生成，请勿手动编辑。",

  // 故事 README
  backToStoryList: "← 返回故事列表",
  seriesLabel: "系列",
  relatedStoriesTitle: "🔗 关联故事",
  basicInfoTitle: "📝 基本信息",
  typeLabel: "类型",
  wordCountLabel: "字数",
  statusLabel: "状态",
  createDateLabel: "首次发布",
  summaryTitle: "📖 简介",
  readingGuideTitle: "📚 阅读指引",
  textFileLabel: "正文文件",
  chaptersTitle: "📑 章节列表",
  licenseOriginalText:
    "本作品采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可证。你可以署名共享、非商业使用，修改后的作品需沿用相同许可。",
  licenseFanficText: (work, author) =>
    `本作品是基于${work}（原作：${author}）的同人创作。原作角色、世界观等元素的版权归原作者及版权方所有。`,
  licenseFanficNote: "本人对原创情节和对话主张著作权，采用 CC BY-NC-SA 4.0 许可。**禁止将本故事用于任何商业用途。**",

  // 类型/状态映射
  type: {
    original: "原创",
    fanfic: "二创",
  },
  status: {
    completed: "已完结",
    ongoing: "连载中",
  },

  // 字数格式
  wordCountFormat: {
    thousand: (n) => `约 ${n} 千字`,
    char: (n) => `约 ${n} 字`,
    empty: "字数待补充",
  },
  totalWordCountFormat: {
    tenThousand: (n) => `约 ${n} 万字`,
    thousand: (n) => `约 ${n} 千字`,
    char: (n) => `约 ${n} 字`,
  },

  // CLI 输出
  scanning: "🔍 扫描故事目录...",
  buildSuccess: (count) => `✅ 构建完成！共生成 ${count} 个故事 README + 1 个根 README，总计 ${count} 个故事`,
  buildFail: "❌ 构建失败，存在以下错误：",
  validateOnly: (count) => `✅ 校验通过，共 ${count} 个故事配置有效`,
  duplicateNumberWarning: (num) => `⚠️ 检测到重复序号 "${num}"，排序可能不符合预期`,
  renameWarning: (oldName, newName) => `⚠️ 检测到文件夹重命名：${oldName} → ${newName}`,
  renameWarningHint: () =>
    `   请勿重命名已有故事文件夹，以保持链接稳定。如需调整顺序，请使用 config.json 的 series / seriesOrder 字段。`,
  generatingReadmes: "📝 生成故事 README...",
  generatingRoot: "  ✅ README.md",
  missingConfig: (folder) => `❌ ${folder}: 缺少 config.json`,
  configParseError: (folder, msg) => `❌ ${folder}: config.json 解析失败 - ${msg}`,
  autoWordCount: (folder, wc, saved) =>
    `📊 ${folder}: 自动计算字数为 ${wc}${saved ? "" : "（未写回，使用 --save-counts 持久化）"}`,
  generatedText: (folder) => `📄 ${folder}: 已生成 text.md（合并 章节内容）`,
  mergedWarning: (folder) => `⚠️ ${folder}: 未找到 text.md，已从 chapter-*.md 合并`,
  storyReadmeDone: (folder) => `  ✅ ${folder}/README.md`,
  noSummary: "无简介",
  skippedExport: (n) => `  ⚠️ ${n} 个故事已跳过`,

  // story new 命令
  newMissingTitle: `请指定故事标题！
  用法：story new "标题" [--type=original|fanfic] [--author="原作名"] [--creator="原作者"] [--lang=zh|en]

  示例：
    story new "我的第一个故事"
    story new "二创故事" --type=fanfic --author="原作名" --creator="原作者" --lang=en`,
  newTypeInvalid: (choices, got) => `--type 必须是 ${choices.map((v) => `"${v}"`).join(" 或 ")}，当前为 "${got}"`,
  newFanficRequiresAuthor: `二创故事必须指定 --author="原作名"`,
  newFanficRequiresCreator: `二创故事必须指定 --creator="原作者"`,
  newFolderExists: (folder) => `目录已存在：${folder}`,
  newConfigInvalid: (issues) => `配置校验失败：${issues}`,
  newCreated: (folderName, type) => `✅ 已创建故事：${folderName}/
   ├── config.json (type: ${type})
   └── text.md`,
  newNextSteps: (folderName) => `
后续步骤：
  1. 编辑 ${folderName}/config.json
  2. 在 ${folderName}/text.md 中写作
  3. 运行：story build
`,

  // Watch 模式
  watchStart: "监听模式已启动，文件变更自动重建...",
  watchRebuild: (trigger) => `检测到变更（${trigger}），重新构建...`,
  watchDone: (count) => `✅ 重建完成！共 ${count} 个故事`,
  watchHint: "等待文件变更...（Ctrl+C 退出）",
  watchExit: "已退出监听模式",

  // EPUB 导出
  epubExporting: "📚 正在导出 EPUB...",
  epubMissingConfig: (folder) => `❌ ${folder}: 缺少 config.json`,
  epubConfigParse: (folder, msg) => `❌ ${folder}: config.json 解析失败 - ${msg}`,
  epubInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败`,
  epubEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,
  epubImageMissing: (src) => `⚠️ 图片不存在: ${src}`,
  epubImageReadFailed: (src, msg) => `⚠️ 读取图片失败: ${src} - ${msg}`,
  epubExportSuccess: (folder, output, sizeKB, imgCount) => `✅ ${folder} → ${output} (${sizeKB} KB${imgCount})`,
  epubExportFailed: (folder, msg) => `❌ ${folder}: 导出失败 - ${msg}`,
  epubStats: (success, failed) => `📊 导出完成: ${success} 成功, ${failed} 失败`,
  epubOutputDir: (output) => `📁 输出目录: ${output}`,
  epubNoArgsError: `请指定故事标题或使用 --all!\n  Usage:\n    story epub "Title"       # Export one story\n    story epub --all           # Export all stories`,
  epubNotFound: (title) => `未找到匹配 "${title}" 的故事文件夹`,
  epubCoverMissing: (p) => `⚠️ 封面图片不存在: ${p}`,
  epubSvgUnsafe: (p) => `⚠️ 封面 SVG 包含危险内容（脚本/事件属性），已跳过: ${p}`,
  epubCoverReadFailed: (p, msg) => `⚠️ 读取封面图片失败: ${p} - ${msg}`,
  epubLicenseOriginal: "本作品采用 CC BY-NC-SA 4.0 许可证。你可以署名共享、非商业使用，修改后的作品需沿用相同许可。",
  epubLicenseFanfic: (work, author) =>
    `本作品是基于${work}（原作：${author}）的同人创作。原作角色、世界观等元素的版权归原作者及版权方所有。禁止将本故事用于任何商业用途。`,

  // HTML 导出
  htmlExporting: "🌐 正在导出 HTML 站点...",
  htmlExportSuccess: (count, output) => `✅ HTML 导出完成：${count} 个故事 → ${output}/index.html`,
  htmlInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败，已跳过`,
  htmlEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

  // 纯文本导出
  txtExporting: "📄 正在导出纯文本...",
  txtExportSuccess: (count, output) => `✅ 纯文本导出完成：${count} 个故事 → ${output}/`,
  txtInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败，已跳过`,
  txtEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

  // JSON 导出
  jsonExporting: "🔗 正在导出结构化 JSON...",
  jsonExportSuccess: (count, output) => `✅ JSON 导出完成：${count} 个故事 → ${output}`,
  jsonEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

  // Markdown 导出（合并单文件）
  mdExporting: "📄 正在导出合并 Markdown...",
  mdExportSuccess: (count, output) => `✅ Markdown 导出完成：${count} 个故事 → ${output}/`,
  mdEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

  // Embeddings 导出
  embeddingsExporting: "🧠 正在导出文本块（embeddings）...",
  embeddingsExportSuccess: (chunks, output) => `✅ Embeddings 导出完成：${chunks} 个文本块 → ${output}`,
  embeddingsEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

  // Demo 模式
  demoGenerating: "🎬 正在生成示例故事仓库...",
  demoDone: "✅ 示例故事仓库已生成！",
  demoExplain: (count) => `已创建 ${count} 个示例故事。你可以：

  1. 编辑任意故事的 text.md 开始写作
  2. 运行 \`story build\` 生成 README（已自动生成）
  3. 运行 \`story epub "星河入梦"\` 导出 EPUB
  4. 运行 \`story export html\` 导出静态站点

  本目录现在是一个功能完整的故事仓库，随时可以提交到 Git！`,

  // Stats 创作统计
  statsScanning: "📊 正在统计创作数据...",
  statsStoryCount: (count, completed, ongoing) => `📚 故事: ${count} 部 (${completed} 完成 / ${ongoing} 连载中)`,
  statsTotalWords: (words, chapters) => `📝 总字数: ${words} (${chapters} 个章节)`,
  statsSeries: (name, count, completion) => `📈 系列「${name}」: ${count} 部 → ${completion}`,
  statsStandalone: (count) => `📌 独立故事: ${count} 部`,
  statsActivity: (thisMonth, lastMonth) => `🔥 写作活跃度: 本月 ${thisMonth} (上月 ${lastMonth})`,
  statsNoGit: "⚠️ 非 Git 仓库，无法统计写作活跃度",
  statsHealthTitle: (count) => `⚠️ 健康度检查: ${count} 项警告`,
  statsStaleWordCount: (folder, config, actual) => `    [过期字数] ${folder}: config=${config}, 实际=${actual}`,
  statsHealthy: "✅ 健康度检查: 全部正常",
  statsThisMonth: "本月",
  statsLastMonth: "上月",

  // JSON 导入
  importJsonReading: "📥 正在从 JSON 导入故事...",
  importJsonFileNotFound: (p) => `文件不存在: ${p}`,
  importJsonEmptyInput: "stdin 输入为空，请通过 --file 指定文件或通过管道传入 JSON",
  importJsonUsage: `Usage:
story import json --file=stories.json    # 从文件导入
story import json < stories.json          # 从 stdin 导入
story import json --file=stories.json --output=my-stories/  # 指定输出目录`,
  importJsonReadFailed: (msg) => `读取输入失败 - ${msg}`,
  importJsonParseError: (msg) => `JSON 解析失败 - ${msg}`,
  importJsonInvalidFormat: 'JSON 格式无效：根结构应为 { "stories": [...] }',
  importJsonMissingTitle: (i) => `第 ${i} 条故事缺少 title 字段，已跳过`,
  importJsonDone: (success, failed) => `📥 导入完成：${success} 成功, ${failed} 失败`,
  importJsonOutputDir: (dir) => `输出目录: ${dir}`,
  importJsonNextStep: "运行 `story build` 生成 README",
  importJsonValidationFailed: (title, issues) => `  ⚠️ ${title}: ${issues}`,
  importJsonTitleExists: (title) => `  ⚠️ ${title}: 相同标题的故事已存在，已跳过`,
  importJsonDirExists: (folder) => `  ⚠️ ${folder}: 目录已存在，已跳过`,

  // 编码检测
  encodingGbkWarning: (filePath) =>
    `⚠️ ${filePath} 可能使用 GBK/GB2312 编码，请用 VS Code 或记事本「另存为 UTF-8」后重新运行`,
  encodingUnknownWarning: (filePath) => `⚠️ ${filePath} 不是有效的 UTF-8 编码，请将文件转换为 UTF-8 后重新运行`,

  // 合规检查（story validate）
  complianceTitle: "📐 正在检查仓库合规性...",
  compliancePass: (count) => `✅ 合规检查通过：${count} 个故事均符合 Story-Repo 规范`,
  complianceFail: (errorCount, warningCount) => `❌ 合规检查未通过：${errorCount} 个错误，${warningCount} 个警告`,
  complianceInvalidFolderName: (folder) => `目录名不符合规范 "NN-名称"（至少两位数字）: ${folder}`,
  complianceDuplicateNumber: (num, existing, folder) => `重复序号 "${num}"：${existing} 与 ${folder}`,
  complianceMissingConfig: (folder) => `${folder}: 缺少 config.json`,
  complianceInvalidConfig: (folder) => `${folder}: config.json 无效（无法解析或不符合 schema）`,
  complianceMissingContent: (folder) => `${folder}: 缺少正文（需 text.md 或 chapter-*.md）`,
  complianceEncoding: (folder, file) => `${folder}/${file} 可能是非 UTF-8 编码`,

  // story link 关联故事
  linkUsage: `用法：story link <sourceFolder> <targetFolder>  |  story link --remove=<target> <source>  |  story link --list [source]`,
  linkNotFound: (folder) => `找不到故事目录：${folder}`,
  linkMissingConfig: (folder) => `${folder}: 缺少 config.json`,
  linkParseError: (folder) => `${folder}: config.json 解析失败`,
  linkList: (source, links) => `${source}: ${links}`,
  linkNone: "无关联",
  linkNotPresent: (source, target) => `${source} 未关联 ${target}`,
  linkRemoved: (source, target) => `已移除 ${source} → ${target}`,
  linkSelf: (source) => `不能将 ${source} 关联到自身`,
  linkAlreadyPresent: (source, target) => `${source} 已关联 ${target}（幂等）`,
  linkAdded: (source, target) => `已添加 ${source} → ${target}`,

  // build 关联建议
  linkSuggestionTitle: "🔗 检测到可能的关联故事（未自动写入，可手动确认）：",
  linkSuggestionLine: (source, target, shared) => `  - ${source} ↔ ${target}（共享 ${shared} 个关键词）`,
  linkSuggestionHint: () => `    如需确认关联，请运行：story link "${"<源>"}" "${"<目标>"}"`,
}
