import assert from "node:assert"
import { test } from "node:test"
import { formatStatus, formatType, getLocale, resolveLang } from "../src/i18n/index.ts"

test("getLocale 返回中文文案", () => {
  const zh = getLocale("zh")
  assert.strictEqual(zh.rootTitle, "📚 我的故事集")
  assert.strictEqual(zh.type.original, "原创")
  assert.strictEqual(zh.status.ongoing, "连载中")
})

test("getLocale 返回英文文案", () => {
  const en = getLocale("en")
  assert.strictEqual(en.rootTitle, "📚 My Stories")
  assert.strictEqual(en.type.original, "Original")
  assert.strictEqual(en.status.completed, "Completed")
})

test("getLocale 未知语言回退英文", () => {
  assert.strictEqual(getLocale("jp").rootTitle, "📚 My Stories")
})

test("formatType 格式化类型", () => {
  assert.strictEqual(formatType("original", "zh"), "原创")
  assert.strictEqual(formatType("fanfic", "en"), "Fan Fiction")
  assert.strictEqual(formatType("unknown", "zh"), "unknown")
})

test("formatType 支持仓库级自定义标签", () => {
  const labels = {
    translation: { zh: "翻译", en: "Translation" },
    original: { zh: "自定原创", en: "Custom Original" },
  }
  // 自定义类型使用标签
  assert.strictEqual(formatType("translation", "zh", labels), "翻译")
  assert.strictEqual(formatType("translation", "en", labels), "Translation")
  // 内置类型标签优先于内置映射
  assert.strictEqual(formatType("original", "zh", labels), "自定原创")
  assert.strictEqual(formatType("original", "en", labels), "Custom Original")
  // 无标签时回退内置映射
  assert.strictEqual(formatType("original", "zh"), "原创")
})

test("formatStatus 支持仓库级自定义标签", () => {
  const labels = {
    planned: { zh: "计划中", en: "Planned" },
    completed: { zh: "已完结自定义", en: "Custom Completed" },
  }
  // 自定义状态使用标签
  assert.strictEqual(formatStatus("planned", "zh", labels), "计划中")
  assert.strictEqual(formatStatus("planned", "en", labels), "Planned")
  // 内置状态标签优先于内置映射
  assert.strictEqual(formatStatus("completed", "zh", labels), "已完结自定义")
  // 无标签时回退内置映射
  assert.strictEqual(formatStatus("completed", "zh"), "已完结")
})

test("resolveLang 解析语言", () => {
  assert.strictEqual(resolveLang({ language: "en" }), "en")
  assert.strictEqual(resolveLang({}), "zh")
  assert.strictEqual(resolveLang({ language: "" }), "zh")
})

test("中英文文案关键字段完整性", () => {
  const zh = getLocale("zh")
  const en = getLocale("en")
  const keys = [
    "rootTitle",
    "rootStats",
    "rootWelcome",
    "storyListHeader",
    "storyListHint",
    "howToAddTitle",
    "architectureTitle",
    "sponsorTitle",
    "licenseTitle",
    "backToStoryList",
    "basicInfoTitle",
    "typeLabel",
    "wordCountLabel",
    "statusLabel",
    "createDateLabel",
    "summaryTitle",
    "readingGuideTitle",
    "textFileLabel",
    "chaptersTitle",
    "licenseOriginalText",
    "licenseFanficText",
    "licenseFanficNote",
    "autoGenerated",
  ]
  for (const key of keys) {
    assert.ok((zh as unknown as Record<string, unknown>)[key] !== undefined, `zh missing: ${key}`)
    assert.ok((en as unknown as Record<string, unknown>)[key] !== undefined, `en missing: ${key}`)
  }
})

test("英文 totalWordCountFormat 不包含中文字符", () => {
  const en = getLocale("en")
  assert.strictEqual(en.totalWordCountFormat.tenThousand(18000), "~18.0K words")
  assert.ok(!/[一-龥]/.test(en.totalWordCountFormat.tenThousand(18000)))
})
