import assert from "node:assert"
import { test } from "node:test"
import { formatStatus, formatType, getLocale, resolveLang } from "../src/i18n/index.ts"

test("getLocale 返回中文文案", () => {
  const zh = getLocale("zh")
  assert.strictEqual(zh.rootTitle, "📚 我的故事集")
  assert.strictEqual(zh.type.original, "原创")
  assert.strictEqual(zh.status.ongoing, "连载中")
})

test("getLocale 返回英文文案", () => {
  const en = getLocale("en")
  assert.strictEqual(en.rootTitle, "📚 My Stories")
  assert.strictEqual(en.type.original, "Original")
  assert.strictEqual(en.status.completed, "Completed")
})

test("getLocale 未知语言回退英文", () => {
  assert.strictEqual(getLocale("jp").rootTitle, "📚 My Stories")
})

test("formatType 格式化类型", () => {
  assert.strictEqual(formatType("original", "zh"), "原创")
  assert.strictEqual(formatType("fanfic", "en"), "Fan Fiction")
  assert.strictEqual(formatType("unknown", "zh"), "unknown")
})

test("formatType 支持仓库级自定义标签", () => {
  const labels = {
    translation: { zh: "翻译", en: "Translation" },
    original: { zh: "自定原创", en: "Custom Original" },
  }
  // 自定义类型使用标签
  assert.strictEqual(formatType("translation", "zh", labels), "翻译")
  assert.strictEqual(formatType("translation", "en", labels), "Translation")
  // 内置类型标签优先于内置映射
  assert.strictEqual(formatType("original", "zh", labels), "自定原创")
  assert.strictEqual(formatType("original", "en", labels), "Custom Original")
  // 无标签时回退内置映射
  assert.strictEqual(formatType("original", "zh"), "原创")
})

test("formatStatus 支持仓库级自定义标签", () => {
  const labels = {
    planned: { zh: "计划中", en: "Planned" },
    completed: { zh: "已完结自定义", en: "Custom Completed" },
  }
  // 自定义状态使用标签
  assert.strictEqual(formatStatus("planned", "zh", labels), "计划中")
  assert.strictEqual(formatStatus("planned", "en", labels), "Planned")
  // 内置状态标签优先于内置映射
  assert.strictEqual(formatStatus("completed", "zh", labels), "已完结自定义")
  // 无标签时回退内置映射
  assert.strictEqual(formatStatus("completed", "zh"), "已完结")
})

test("resolveLang 解析语言", () => {
  assert.strictEqual(resolveLang({ language: "en" }), "en")
  assert.strictEqual(resolveLang({}), "zh")
  assert.strictEqual(resolveLang({ language: "" }), "zh")
})

test("中英文文案关键字段完整性", () => {
  const zh = getLocale("zh")
  const en = getLocale("en")
  const keys = [
    "rootTitle",
    "rootStats",
    "rootWelcome",
    "storyListHeader",
    "storyListHint",
    "howToAddTitle",
    "architectureTitle",
    "sponsorTitle",
    "licenseTitle",
    "backToStoryList",
    "basicInfoTitle",
    "typeLabel",
    "wordCountLabel",
    "statusLabel",
    "createDateLabel",
    "summaryTitle",
    "readingGuideTitle",
    "textFileLabel",
    "chaptersTitle",
    "licenseOriginalText",
    "licenseFanficText",
    "licenseFanficNote",
    "autoGenerated",
    // 新增：export 跳过计数 / story new / EPUB 许可证 / import-json 警告
    "skippedExport",
    "newMissingTitle",
    "newTypeInvalid",
    "newFanficRequiresAuthor",
    "newFanficRequiresCreator",
    "newFolderExists",
    "newConfigInvalid",
    "newCreated",
    "newNextSteps",
    "epubLicenseOriginal",
    "epubLicenseFanfic",
    "importJsonValidationFailed",
    "importJsonTitleExists",
    "importJsonDirExists",
    // 新增：合规检查 / story link / 关联建议 / embeddings
    "complianceTitle",
    "compliancePass",
    "complianceFail",
    "complianceInvalidFolderName",
    "complianceDuplicateNumber",
    "complianceMissingConfig",
    "complianceInvalidConfig",
    "complianceMissingContent",
    "complianceEncoding",
    "linkUsage",
    "linkNotFound",
    "linkMissingConfig",
    "linkParseError",
    "linkList",
    "linkNone",
    "linkNotPresent",
    "linkRemoved",
    "linkSelf",
    "linkAlreadyPresent",
    "linkAdded",
    "linkSuggestionTitle",
    "linkSuggestionLine",
    "linkSuggestionHint",
    "embeddingsExporting",
    "embeddingsExportSuccess",
    "embeddingsEmptyContent",
    "relatedStoriesTitle",
  ]
  for (const key of keys) {
    assert.ok((zh as unknown as Record<string, unknown>)[key] !== undefined, `zh missing: ${key}`)
    assert.ok((en as unknown as Record<string, unknown>)[key] !== undefined, `en missing: ${key}`)
  }
})

test("中英文文案键集合完全一致（防止 i18n 双侧漂移）", () => {
  const zh = getLocale("zh") as unknown as Record<string, unknown>
  const en = getLocale("en") as unknown as Record<string, unknown>
  const zhKeys = Object.keys(zh).sort()
  const enKeys = Object.keys(en).sort()
  assert.deepStrictEqual(zhKeys, enKeys, "zh 与 en 的文案键应完全一致")
})

test("新增文案的中英文本均非空且执行无误", () => {
  const zh = getLocale("zh")
  const en = getLocale("en")
  assert.ok(zh.skippedExport(3).length > 0)
  assert.ok(en.skippedExport(3).length > 0)
  assert.ok(zh.newMissingTitle.length > 0)
  assert.ok(en.newMissingTitle.length > 0)
  assert.ok(zh.newTypeInvalid(["original"], "invalid").length > 0)
  assert.ok(en.newTypeInvalid(["original"], "invalid").length > 0)
  assert.ok(zh.newCreated("01-测试", "original").includes("01-测试"))
  assert.ok(en.newCreated("01-Test", "original").includes("01-Test"))
  assert.ok(zh.epubLicenseOriginal.length > 0)
  assert.ok(en.epubLicenseOriginal.length > 0)
  assert.ok(zh.epubLicenseFanfic("原作", "作者").includes("原作"))
  assert.ok(en.epubLicenseFanfic("Work", "Author").includes("Work"))
})

test("英文 totalWordCountFormat 不包含中文字符", () => {
  const en = getLocale("en")
  assert.strictEqual(en.totalWordCountFormat.tenThousand(18000), "~18.0K words")
  assert.ok(!/[一-龥]/.test(en.totalWordCountFormat.tenThousand(18000)))
})
