import fs from "node:fs"
import path from "node:path"
import { parseArgs } from "../args.ts"
import { loadStories } from "../core/loader.ts"
import { EXCLUDE_DIRS } from "../core/scanner.ts"
import type { StoryData, StorySummary } from "../core/types.ts"
import { getLocale } from "../i18n/index.ts"
import { generateRootReadme, generateStoryReadme } from "../render/readme.ts"
import { detectCliLang, detectRenames } from "../utils/cli-utils.ts"
import { formatError } from "../utils/errors.ts"
import { templatesDir } from "../utils/paths.ts"

/**
 * 生成所有故事 README 与根 README
 * @param rootDir 项目根目录
 * @param stories 故事列表
 * @param cliLang CLI 输出语言
 * @param onlyFolder 仅重建指定故事的 README（watch 增量模式），其余故事 README 保持不变
 * @param logger 日志输出函数（默认 console.log；MCP Server 可传入收集器避免拦截全局）
 * @returns 生成的故事 README 数量
 */
export function generateReadmes(
  rootDir: string,
  stories: StoryData[],
  cliLang = "zh",
  onlyFolder?: string,
  logger: (msg: string) => void = (msg) => console.log(msg),
): number {
  const locale = getLocale(cliLang)
  logger(`\n${locale.generatingReadmes}`)
  const templatePath = path.join(templatesDir, "story-template.md")
  let readmeCount = 0

  for (const story of stories) {
    const { folder, config } = story
    // 增量模式：跳过非目标故事（根 README 仍会全量重建以反映最新索引）
    if (onlyFolder && folder !== onlyFolder) continue

    const folderPath = path.join(rootDir, folder)
    const lang = story.lang
    const storyLocale = getLocale(lang)

    const renderData: Record<string, unknown> = {
      ...config,
      chapters: story.chapters,
      lang,
      typeDisplay: story.typeDisplay,
      statusDisplay: story.statusDisplay,
      backToStoryList: storyLocale.backToStoryList,
      seriesLabel: storyLocale.seriesLabel,
      basicInfoTitle: storyLocale.basicInfoTitle,
      typeLabel: storyLocale.typeLabel,
      wordCountLabel: storyLocale.wordCountLabel,
      statusLabel: storyLocale.statusLabel,
      createDateLabel: storyLocale.createDateLabel,
      summaryTitle: storyLocale.summaryTitle,
      readingGuideTitle: storyLocale.readingGuideTitle,
      textFileLabel: storyLocale.textFileLabel,
      chaptersTitle: storyLocale.chaptersTitle,
      licenseTitle: storyLocale.licenseTitle,
      licenseText:
        config.type === "original"
          ? storyLocale.licenseOriginalText
          : storyLocale.licenseFanficText(config.originalWork || "", config.originalAuthor || ""),
      licenseNote: config.type === "fanfic" ? storyLocale.licenseFanficNote : "",
      autoGenerated: storyLocale.autoGenerated,
    }

    generateStoryReadme(folderPath, templatePath, renderData)
    logger(locale.storyReadmeDone(folder))
    readmeCount++
  }

  const storySummaries: Array<Omit<StorySummary, "lang"> & { lang: string }> = stories.map((s) => ({
    folder: s.folder,
    title: s.config.title,
    typeDisplay: s.typeDisplay,
    wordCount: s.wordCount,
    statusDisplay: s.statusDisplay,
    summary: s.config.summary || "",
    rawWordCount: s.rawWordCount,
    lang: s.lang,
    series: s.config.series,
    seriesOrder: s.config.seriesOrder,
    volume: s.config.volume,
  }))

  generateRootReadme(rootDir, storySummaries)
  logger(locale.generatingRoot)

  return readmeCount
}

/**
 * 运行 build 命令
 * @param rootDir 项目根目录
 * @param args 命令行参数
 */
export async function runBuild(rootDir: string, args: string[]): Promise<number> {
  const { options } = parseArgs(args)
  const validateOnly = !!options["validate-only"]
  const saveCounts = !!options["save-counts"]
  const watch = !!options.watch
  // CLI 输出语言：根据系统环境变量 LANG 检测，默认中文
  const cliLang = detectCliLang()
  const locale = getLocale(cliLang)

  if (watch) {
    runWatchMode(rootDir, { validateOnly, saveCounts, cliLang })
    return 0
  }

  // 检测暂存区中是否有故事文件夹重命名（软安全网，不阻断构建）
  const renames = detectRenames(rootDir)
  for (const rename of renames) {
    const [oldName, newName] = rename.split(" → ")
    console.log(locale.renameWarning(oldName ?? "", newName ?? ""))
    console.log(locale.renameWarningHint())
  }

  console.log(locale.scanning, "\n")

  const { stories, issues, warnings } = await loadStories(rootDir, saveCounts, cliLang, validateOnly)

  for (const w of warnings) {
    console.log(w)
  }

  if (issues.length > 0) {
    console.error(`\n${locale.buildFail}`)
    for (const issue of issues) {
      console.error(`  ❌ ${issue.message}`)
    }
    return 1
  }

  if (validateOnly) {
    console.log(`\n${locale.validateOnly(stories.length)}`)
    return 0
  }

  generateReadmes(rootDir, stories, cliLang)
  console.log(`\n${locale.buildSuccess(stories.length)}`)
  return 0
}

/**
 * Watch 模式：监听仓库变更并自动重建
 * 每次 rebuild 后重新扫描故事目录，捕获新增/删除的目录
 * @param rootDir 项目根目录
 * @param options watch 模式选项
 */
function runWatchMode(rootDir: string, options: { validateOnly: boolean; saveCounts: boolean; cliLang: string }): void {
  const { validateOnly, saveCounts, cliLang } = options
  const locale = getLocale(cliLang)
  console.log(`👀 ${locale.watchStart}`)

  const debounceMs = 300
  let timer: ReturnType<typeof setTimeout> | null = null
  let rebuilding = false

  // 监听根目录下的直接子目录和文件（不递归，避免 node_modules 等噪音）
  const watchers: fs.FSWatcher[] = []
  const watched = new Set<string>()

  const watchDir = (dir: string, folderHint?: string) => {
    if (watched.has(dir)) return
    watched.add(dir)

    try {
      const watcher = fs.watch(dir, (_event, filename) => {
        if (!filename) return

        // 忽略常见噪音
        const name = filename.toString()
        if (name.startsWith(".")) return
        if (name === "node_modules") return

        debouncedBuild(name, folderHint)
      })
      watchers.push(watcher)

      // 递归子目录（但排除基础设施目录）
      if (fs.existsSync(dir)) {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          if (entry.isDirectory() && !EXCLUDE_DIRS.has(entry.name)) {
            // 子目录继承父级故事归属（根目录 → 故事目录 → 故事子目录）
            const childHint = folderHint ?? entry.name
            watchDir(path.join(dir, entry.name), childHint)
          }
        }
      }
    } catch {
      // 目录可能被删除，忽略
    }
  }

  /**
   * 重新扫描故事目录并监听新出现的故事子目录
   * 解决"新增故事文件夹后其内部变更不触发 rebuild"的问题
   */
  const rescanStoryDirs = () => {
    try {
      // 新故事文件夹也是 NN- 前缀，需要监听其内部变更
      for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
        if (entry.isDirectory() && !EXCLUDE_DIRS.has(entry.name)) {
          watchDir(path.join(rootDir, entry.name), entry.name)
        }
      }
    } catch {
      // 扫描失败静默忽略
    }
  }

  const doBuild = async (trigger: string, folderHint?: string) => {
    if (rebuilding) return
    rebuilding = true
    console.log(`\n🔨 ${locale.watchRebuild(trigger)}`)

    try {
      const { stories, issues, warnings } = await loadStories(rootDir, saveCounts, cliLang, validateOnly)

      for (const w of warnings) {
        console.log(w)
      }

      // 每次 rebuild 后重新扫描，监听新增的故事目录
      rescanStoryDirs()

      if (issues.length > 0) {
        console.error(`\n${locale.buildFail}`)
        for (const issue of issues) {
          console.error(`  ❌ ${issue.message}`)
        }
      } else if (!validateOnly) {
        generateReadmes(rootDir, stories, cliLang, folderHint)
        console.log(`${locale.watchDone(stories.length)}`)
      } else {
        console.log(`${locale.validateOnly(stories.length)}`)
      }
    } catch (e) {
      // 捕获未处理的异常（如 I/O 错误），打印后继续监听而不是崩溃
      console.error(formatError(e))
      if (process.env.DEBUG && e instanceof Error && e.stack) {
        console.error(e.stack)
      }
    } finally {
      rebuilding = false
    }
  }

  const debouncedBuild = (trigger: string, folderHint?: string) => {
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => {
      void doBuild(trigger, folderHint)
      timer = null
    }, debounceMs)
  }

  watchDir(rootDir)

  console.log(locale.watchHint)

  // 初始构建（包含首次 rescanStoryDirs）
  void doBuild("initial")

  // Ctrl+C 清理
  process.on("SIGINT", () => {
    for (const w of watchers) w.close()
    console.log(`\n👋 ${locale.watchExit}`)
    process.exit(0)
  })
}
