import { execSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { getSponsorImages } from "../core/scanner.ts"
import { groupAndSortStories } from "../core/sort.ts"
import type { Language, StorySummary } from "../core/types.ts"
import { getLocale } from "../i18n/index.ts"
import { templatesDir } from "../utils/paths.ts"
import { formatTotalWordCount } from "../utils/word-count.ts"
import { renderTemplate } from "./template.ts"

/**
 * 生成单个故事的 README.md
 * @param folderPath 故事文件夹路径
 * @param templatePath 故事模板路径
 * @param config 故事配置
 */
export function generateStoryReadme(folderPath: string, templatePath: string, config: Record<string, unknown>): void {
  const content = renderTemplate(templatePath, config)
  fs.writeFileSync(path.join(folderPath, "README.md"), content, "utf-8")
}

/**
 * 截断简介到指定长度
 * @param summary 原始简介
 * @param maxLength 最大长度
 * @returns 截断后的简介
 */
function truncateSummary(summary: string, maxLength = 120): string {
  if (!summary) return ""
  // 1. 折叠换行/多余空白为单个空格，避免破坏 Markdown 表格
  // 2. 转义管道符，避免作为表格分隔符被解析
  const singleLine = summary.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim()
  return singleLine.length > maxLength ? `${singleLine.slice(0, maxLength)}...` : singleLine
}

/**
 * 获取 git 最后提交时间（若无 git 则返回当前日期）
 * @param rootDir 项目根目录
 * @returns 格式化日期（YYYY-MM-DD）
 */
function getLastUpdated(rootDir: string): string {
  try {
    const result = execSync("git log -1 --format=%cs", {
      cwd: rootDir,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    })
    const date = result.trim()
    if (/^\d{4}-\d{2}-\d{2}$/.test(date)) return date
  } catch {
    // git 不可用时回退到当前日期
  }
  return new Date().toISOString().slice(0, 10)
}

/**
 * 生成根目录 README.md（模板驱动）
 * @param rootDir 项目根目录
 * @param stories 故事列表（含展示字段）
 * @param templatePath 根 README 模板路径（默认使用内置模板）
 */
export function generateRootReadme(
  rootDir: string,
  stories: Array<Omit<StorySummary, "lang"> & { lang: string }>,
  templatePath?: string,
): void {
  // 总字数（基于原始字数累加）
  const totalRaw = stories.reduce((sum, s) => sum + (s.rawWordCount || 0), 0)
  // 根 README 语言：如果所有故事都是英文则用英文，否则用中文
  const allEnglish = stories.length > 0 && stories.every((s) => s.lang === "en")
  const lang: Language = allEnglish ? "en" : "zh"
  const locale = getLocale(lang)

  const totalWordCount = formatTotalWordCount(totalRaw, lang)
  const lastUpdated = getLastUpdated(rootDir)

  // 赞助区块：仅当约定目录 assets/sponsor/ 存在图片时显示
  const sponsorImages = getSponsorImages(rootDir)
  const hasSponsor = sponsorImages.length > 0

  // 按系列分组 + 排序（物理坐标永不更改，逻辑坐标自由调整）
  const { groups: seriesGroups, ungrouped } = groupAndSortStories(stories)

  const toRow = (story: Omit<StorySummary, "lang"> & { lang: string }, num: string) => ({
    num,
    folder: story.folder,
    title: story.title,
    typeDisplay: story.typeDisplay,
    wordCount: story.wordCount,
    statusDisplay: story.statusDisplay,
    summary: truncateSummary(story.summary),
  })

  // 全局编号：系列组先遍历，独立故事延续编号
  let counter = 1
  const seriesGroupRows = seriesGroups.map((group) => ({
    name: group.name,
    stories: group.stories.map((s) => toRow(s, String(counter++).padStart(2, "0"))),
  }))
  const ungroupedRows = ungrouped.map((s) => toRow(s, String(counter++).padStart(2, "0")))
  const storyRows = [...seriesGroupRows.flatMap((g) => g.stories), ...ungroupedRows]

  const renderData: Record<string, unknown> = {
    rootTitle: locale.rootTitle,
    rootStats: locale.rootStats(stories.length, totalWordCount, lastUpdated),
    rootWelcome: locale.rootWelcome,
    tocLabel: locale.tocLabel,
    tocStoryList: locale.tocStoryList,
    tocHowToAdd: locale.tocHowToAdd,
    tocArchitecture: locale.tocArchitecture,
    tocSponsor: locale.tocSponsor,
    tocLicense: locale.tocLicense,
    storyListTitle: locale.storyListTitle,
    storyListHeader: locale.storyListHeader,
    storyListHint: locale.storyListHint,
    storyRows,
    seriesGroups: seriesGroupRows,
    ungroupedStories: ungroupedRows,
    hasSeries: seriesGroupRows.length > 0,
    hasUngrouped: ungroupedRows.length > 0,
    independentStoriesTitle: locale.independentStoriesTitle,
    howToAddTitle: locale.howToAddTitle,
    howToAddDesc: locale.howToAddDesc,
    howToAddStep1: locale.howToAddStep1,
    howToAddStep2: locale.howToAddStep2,
    howToAddStep3: locale.howToAddStep3,
    architectureTitle: locale.architectureTitle,
    architectureDesc: locale.architectureDesc,
    hasSponsor,
    sponsorTitle: locale.sponsorTitle,
    sponsorSummary: locale.sponsorSummary,
    sponsorImages: sponsorImages.map((img) => ({
      src: `./${img}`,
      alt: path.basename(img, path.extname(img)),
    })),
    licenseTitle: locale.licenseTitle,
    licenseOriginal: locale.licenseOriginal,
    licenseFanfic: locale.licenseFanfic,
    autoGenerated: locale.autoGenerated,
  }

  const effectiveTemplatePath = templatePath || path.join(templatesDir, "root-template.md")
  const content = renderTemplate(effectiveTemplatePath, renderData)
  fs.writeFileSync(path.join(rootDir, "README.md"), content, "utf-8")
}
