/**
 * 国际化模块
 * 提供中英文文案映射
 */

import type { Language, StoryStatus, StoryType } from "../core/types.ts"

/** 单个语言的完整文案结构 */
export interface Locale {
  // 根 README
  rootTitle: string
  rootStats: (count: number, wordCount: string, date: string) => string
  rootWelcome: string
  tocLabel: string
  tocStoryList: string
  tocHowToAdd: string
  tocArchitecture: string
  tocSponsor: string
  tocLicense: string
  storyListTitle: string
  storyListHeader: string
  storyListHint: string
  howToAddTitle: string
  howToAddDesc: string
  howToAddStep1: string
  howToAddStep2: string
  howToAddStep3: string
  architectureTitle: string
  architectureDesc: string
  sponsorTitle: string
  sponsorSummary: string
  licenseTitle: string
  licenseOriginal: string
  licenseFanfic: string
  autoGenerated: string

  // 故事 README
  backToStoryList: string
  basicInfoTitle: string
  typeLabel: string
  wordCountLabel: string
  statusLabel: string
  createDateLabel: string
  summaryTitle: string
  readingGuideTitle: string
  textFileLabel: string
  chaptersTitle: string
  licenseOriginalText: string
  licenseFanficText: (work: string, author: string) => string
  licenseFanficNote: string

  // 类型/状态映射
  type: Record<StoryType, string>
  status: Record<StoryStatus, string>

  // 字数格式
  wordCountFormat: {
    thousand: (n: number) => string
    char: (n: number) => string
    empty: string
  }
  totalWordCountFormat: {
    tenThousand: (n: number) => string
    thousand: (n: number) => string
    char: (n: number) => string
  }

  // CLI 输出
  scanning: string
  buildSuccess: (count: number) => string
  buildFail: string
  validateOnly: (count: number) => string
  duplicateNumberWarning: (num: string) => string
  generatingReadmes: string
  generatingRoot: string
  missingConfig: (folder: string) => string
  configParseError: (folder: string, msg: string) => string
  autoWordCount: (folder: string, wc: string, saved: boolean) => string
  generatedText: (folder: string) => string
  mergedWarning: (folder: string) => string
  storyReadmeDone: (folder: string) => string
  noSummary: string

  // Watch 模式
  watchStart: string
  watchRebuild: (trigger: string) => string
  watchDone: (count: number) => string
  watchHint: string
  watchExit: string

  // EPUB 导出
  epubExporting: string
  epubMissingConfig: (folder: string) => string
  epubConfigParse: (folder: string, msg: string) => string
  epubInvalidConfig: (folder: string) => string
  epubEmptyContent: (folder: string) => string
  epubImageMissing: (src: string) => string
  epubImageReadFailed: (src: string, msg: string) => string
  epubExportSuccess: (folder: string, output: string, sizeKB: string, imgCount: string) => string
  epubExportFailed: (folder: string, msg: string) => string
  epubStats: (success: number, failed: number) => string
  epubOutputDir: (output: string) => string
  epubNoArgsError: string
  epubNotFound: (title: string) => string

  // HTML 导出
  htmlExporting: string
  htmlExportSuccess: (count: number, output: string) => string
  htmlInvalidConfig: (folder: string) => string
  htmlEmptyContent: (folder: string) => string

  // 纯文本导出
  txtExporting: string
  txtExportSuccess: (count: number, output: string) => string
  txtInvalidConfig: (folder: string) => string
  txtEmptyContent: (folder: string) => string
}

export const LOCALES: Record<Language, Locale> = {
  zh: {
    // 根 README
    rootTitle: "📚 我的故事集",
    rootStats: (count, wordCount, date) => `✍️ 共 **${count}** 个故事 · **${wordCount}** · 最后更新：${date}`,
    rootWelcome: "欢迎来到我的创作仓库。",
    tocLabel: "📑 目录",
    tocStoryList: "📖 故事列表",
    tocHowToAdd: "📝 如何新增故事",
    tocArchitecture: "🔧 技术架构",
    tocSponsor: "☕ 赞助支持",
    tocLicense: "⚖️ 许可证",
    storyListTitle: "📖 故事列表",
    storyListHeader: "| # | 故事 | 类型 | 字数 | 状态 | 简介 |\n|---|------|------|------|------|------|",
    storyListHint: "> 💡 点击故事标题进入阅读页，正文见各目录下的 `text.md`",
    howToAddTitle: "📝 如何新增故事",
    howToAddDesc: "想添加新故事？请参考 [docs/add-story.md](docs/add-story.md)，只需 3 步即可完成：",
    howToAddStep1: "1. 创建目录 `NN-故事名/`",
    howToAddStep2: "2. 编写 `config.json`",
    howToAddStep3: "3. 运行 `pnpm build`",
    architectureTitle: "🔧 技术架构",
    architectureDesc: "了解本仓库的构建系统与模块设计，请参阅 [docs/architecture.md](docs/architecture.md)。",
    sponsorTitle: "☕ 赞助支持",
    sponsorSummary: "如果你喜欢我的创作，可以请我喝杯咖啡。",
    licenseTitle: "⚖️ 许可证",
    licenseOriginal: "原创故事采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可证。",
    licenseFanfic: "二创故事版权归原作者所有，禁止商用。",
    autoGenerated: "本 README 由脚本自动生成，请勿手动编辑。",

    // 故事 README
    backToStoryList: "← 返回故事列表",
    basicInfoTitle: "📝 基本信息",
    typeLabel: "类型",
    wordCountLabel: "字数",
    statusLabel: "状态",
    createDateLabel: "首次发布",
    summaryTitle: "📖 简介",
    readingGuideTitle: "📚 阅读指引",
    textFileLabel: "正文文件",
    chaptersTitle: "📑 章节列表",
    licenseOriginalText:
      "本作品采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可证。你可以署名共享、非商业使用，修改后的作品需沿用相同许可。",
    licenseFanficText: (work, author) =>
      `本作品是基于${work}（原作：${author}）的同人创作。原作角色、世界观等元素的版权归原作者及版权方所有。`,
    licenseFanficNote: "本人对原创情节和对话主张著作权，采用 CC BY-NC-SA 4.0 许可。**禁止将本故事用于任何商业用途。**",

    // 类型/状态映射
    type: {
      original: "原创",
      fanfic: "二创",
    },
    status: {
      completed: "已完结",
      ongoing: "连载中",
    },

    // 字数格式
    wordCountFormat: {
      thousand: (n) => `约 ${n} 千字`,
      char: (n) => `约 ${n} 字`,
      empty: "字数待补充",
    },
    totalWordCountFormat: {
      tenThousand: (n) => `约 ${n} 万字`,
      thousand: (n) => `约 ${n} 千字`,
      char: (n) => `约 ${n} 字`,
    },

    // CLI 输出
    scanning: "🔍 扫描故事目录...",
    buildSuccess: (count) => `✅ 构建完成！共生成 ${count} 个故事 README + 1 个根 README，总计 ${count} 个故事`,
    buildFail: "❌ 构建失败，存在以下错误：",
    validateOnly: (count) => `✅ 校验通过，共 ${count} 个故事配置有效`,
    duplicateNumberWarning: (num) => `⚠️ 检测到重复序号 "${num}"，排序可能不符合预期`,
    generatingReadmes: "📝 生成故事 README...",
    generatingRoot: "  ✅ README.md",
    missingConfig: (folder) => `❌ ${folder}: 缺少 config.json`,
    configParseError: (folder, msg) => `❌ ${folder}: config.json 解析失败 - ${msg}`,
    autoWordCount: (folder, wc, saved) =>
      `📊 ${folder}: 自动计算字数为 ${wc}${saved ? "" : "（未写回，使用 --save-counts 持久化）"}`,
    generatedText: (folder) => `📄 ${folder}: 已生成 text.md（合并 章节内容）`,
    mergedWarning: (folder) => `⚠️ ${folder}: 未找到 text.md，已从 chapter-*.md 合并`,
    storyReadmeDone: (folder) => `  ✅ ${folder}/README.md`,
    noSummary: "无简介",

    // Watch 模式
    watchStart: "监听模式已启动，文件变更自动重建...",
    watchRebuild: (trigger) => `检测到变更（${trigger}），重新构建...`,
    watchDone: (count) => `✅ 重建完成！共 ${count} 个故事`,
    watchHint: "等待文件变更...（Ctrl+C 退出）",
    watchExit: "已退出监听模式",

    // EPUB 导出
    epubExporting: "📚 正在导出 EPUB...",
    epubMissingConfig: (folder) => `❌ ${folder}: 缺少 config.json`,
    epubConfigParse: (folder, msg) => `❌ ${folder}: config.json 解析失败 - ${msg}`,
    epubInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败`,
    epubEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,
    epubImageMissing: (src) => `⚠️ 图片不存在: ${src}`,
    epubImageReadFailed: (src, msg) => `⚠️ 读取图片失败: ${src} - ${msg}`,
    epubExportSuccess: (folder, output, sizeKB, imgCount) => `✅ ${folder} → ${output} (${sizeKB} KB${imgCount})`,
    epubExportFailed: (folder, msg) => `❌ ${folder}: 导出失败 - ${msg}`,
    epubStats: (success, failed) => `📊 导出完成: ${success} 成功, ${failed} 失败`,
    epubOutputDir: (output) => `📁 输出目录: ${output}`,
    epubNoArgsError: `请指定故事标题或使用 --all!\n  Usage:\n    story epub "Title"       # Export one story\n    story epub --all           # Export all stories`,
    epubNotFound: (title) => `未找到匹配 "${title}" 的故事文件夹`,

    // HTML 导出
    htmlExporting: "🌐 正在导出 HTML 站点...",
    htmlExportSuccess: (count, output) => `✅ HTML 导出完成：${count} 个故事 → ${output}/index.html`,
    htmlInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败，已跳过`,
    htmlEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,

    // 纯文本导出
    txtExporting: "📄 正在导出纯文本...",
    txtExportSuccess: (count, output) => `✅ 纯文本导出完成：${count} 个故事 → ${output}/`,
    txtInvalidConfig: (folder) => `❌ ${folder}: 配置校验失败，已跳过`,
    txtEmptyContent: (folder) => `⚠️ ${folder}: 正文为空，已跳过`,
  },
  en: {
    // Root README
    rootTitle: "📚 My Stories",
    rootStats: (count, wordCount, date) => `✍️ **${count}** stories · **${wordCount}** · Updated: ${date}`,
    rootWelcome: "Welcome to my writing repository.",
    tocLabel: "📑 Table of Contents",
    tocStoryList: "📖 Story List",
    tocHowToAdd: "📝 How to Add a Story",
    tocArchitecture: "🔧 Architecture",
    tocSponsor: "☕ Support",
    tocLicense: "⚖️ License",
    storyListTitle: "📖 Story List",
    storyListHeader: "| # | Story | Type | Words | Status | Summary |\n|---|-------|------|-------|--------|---------|",
    storyListHint: "> 💡 Click a story title to read. Text is in each folder's `text.md`.",
    howToAddTitle: "📝 How to Add a Story",
    howToAddDesc: "Want to add a new story? See [docs/add-story.md](docs/add-story.md) — just 3 steps:",
    howToAddStep1: "1. Create folder `NN-story-name/`",
    howToAddStep2: "2. Write `config.json`",
    howToAddStep3: "3. Run `pnpm build`",
    architectureTitle: "🔧 Architecture",
    architectureDesc: "Learn about the build system and module design in [docs/architecture.md](docs/architecture.md).",
    sponsorTitle: "☕ Support",
    sponsorSummary: "If you like my work, feel free to buy me a coffee.",
    licenseTitle: "⚖️ License",
    licenseOriginal:
      "Original stories are licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/).",
    licenseFanfic: "Fan fiction belongs to original creators. Commercial use prohibited.",
    autoGenerated: "This README was auto-generated. Do not edit manually.",

    // Story README
    backToStoryList: "← Back to Story List",
    basicInfoTitle: "📝 Basic Info",
    typeLabel: "Type",
    wordCountLabel: "Word Count",
    statusLabel: "Status",
    createDateLabel: "First Published",
    summaryTitle: "📖 Summary",
    readingGuideTitle: "📚 Reading Guide",
    textFileLabel: "Text File",
    chaptersTitle: "📑 Chapters",
    licenseOriginalText:
      "This work is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). You are free to share, non-commercially; derivatives must use the same license.",
    licenseFanficText: (work, author) =>
      `This is a fan work based on ${work} (by ${author}). Original characters and world rights belong to the original creators.`,
    licenseFanficNote:
      "Original plot and dialogue are covered by CC BY-NC-SA 4.0. **Commercial use is strictly prohibited.**",

    // Type/status mapping
    type: {
      original: "Original",
      fanfic: "Fan Fiction",
    },
    status: {
      completed: "Completed",
      ongoing: "Ongoing",
    },

    // Word count formats
    wordCountFormat: {
      thousand: (n) => `~${n}K words`,
      char: (n) => `~${n} words`,
      empty: "Word count TBD",
    },
    totalWordCountFormat: {
      tenThousand: (n) => `~${(n / 1000).toFixed(1)}K words`,
      thousand: (n) => `~${Math.round(n / 1000)}K words`,
      char: (n) => `~${n} words`,
    },

    // CLI output
    scanning: "🔍 Scanning story folders...",
    buildSuccess: (count) =>
      `✅ Build complete! Generated ${count} story READMEs + 1 root README (${count} stories total)`,
    buildFail: "❌ Build failed with the following errors:",
    validateOnly: (count) => `✅ Validation passed. ${count} story configs are valid`,
    duplicateNumberWarning: (num) => `⚠️ Duplicate number "${num}" detected, sorting may be unexpected`,
    generatingReadmes: "📝 Generating story READMEs...",
    generatingRoot: "  ✅ README.md",
    missingConfig: (folder) => `❌ ${folder}: missing config.json`,
    configParseError: (folder, msg) => `❌ ${folder}: config.json parse failed - ${msg}`,
    autoWordCount: (folder, wc, saved) =>
      `📊 ${folder}: auto word count = ${wc}${saved ? "" : " (not saved, use --save-counts to persist)"}`,
    generatedText: (folder) => `📄 ${folder}: text.md generated (merged chapters)`,
    mergedWarning: (folder) => `⚠️ ${folder}: text.md not found, merged from chapter-*.md`,
    storyReadmeDone: (folder) => `  ✅ ${folder}/README.md`,
    noSummary: "No summary",

    // Watch mode
    watchStart: "Watch mode started. Auto-rebuilding on file changes...",
    watchRebuild: (trigger) => `Change detected (${trigger}), rebuilding...`,
    watchDone: (count) => `✅ Rebuild complete! ${count} stories`,
    watchHint: "Waiting for file changes... (Ctrl+C to exit)",
    watchExit: "Watch mode exited",

    // EPUB export
    epubExporting: "📚 Exporting EPUB...",
    epubMissingConfig: (folder) => `❌ ${folder}: missing config.json`,
    epubConfigParse: (folder, msg) => `❌ ${folder}: config.json parse failed - ${msg}`,
    epubInvalidConfig: (folder) => `❌ ${folder}: config validation failed`,
    epubEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,
    epubImageMissing: (src) => `⚠️ Image not found: ${src}`,
    epubImageReadFailed: (src, msg) => `⚠️ Failed to read image: ${src} - ${msg}`,
    epubExportSuccess: (folder, output, sizeKB, imgCount) => `✅ ${folder} → ${output} (${sizeKB} KB${imgCount})`,
    epubExportFailed: (folder, msg) => `❌ ${folder}: export failed - ${msg}`,
    epubStats: (success, failed) => `📊 Export complete: ${success} success, ${failed} failed`,
    epubOutputDir: (output) => `📁 Output: ${output}`,
    epubNoArgsError: `Please specify a story title or use --all!\n  Usage:\n    story epub "Title"       # Export one story\n    story epub --all           # Export all stories`,
    epubNotFound: (title) => `No story folder matching "${title}"`,

    // HTML export
    htmlExporting: "🌐 Exporting HTML site...",
    htmlExportSuccess: (count, output) => `✅ HTML export complete: ${count} stories → ${output}/index.html`,
    htmlInvalidConfig: (folder) => `❌ ${folder}: config validation failed, skipped`,
    htmlEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,

    // Plain text export
    txtExporting: "📄 Exporting plain text...",
    txtExportSuccess: (count, output) => `✅ Plain text export complete: ${count} stories → ${output}/`,
    txtInvalidConfig: (folder) => `❌ ${folder}: config validation failed, skipped`,
    txtEmptyContent: (folder) => `⚠️ ${folder}: empty content, skipped`,
  },
}

/**
 * 获取指定语言的文案
 * @param lang 语言代码（zh / en）
 * @returns 文案对象
 */
export function getLocale(lang: string | Language): Locale {
  return LOCALES[lang as Language] || LOCALES.en
}

/**
 * 将类型代码映射为显示文本
 * 优先使用仓库级自定义标签；未配置时回退到内置映射；最后回退到原始代码
 * @param typeCode 类型代码（original / fanfic / 自定义）
 * @param lang 语言
 * @param labels 仓库级自定义标签（可选）
 * @returns 显示文本
 */
export function formatType(typeCode: string, lang: Language, labels?: Record<string, Record<string, string>>): string {
  if (labels?.[typeCode]?.[lang]) return labels[typeCode][lang]
  const locale = getLocale(lang)
  return locale.type[typeCode as StoryType] || typeCode
}

/**
 * 将状态代码映射为显示文本
 * 优先使用仓库级自定义标签；未配置时回退到内置映射；最后回退到原始代码
 * @param statusCode 状态代码（completed / ongoing / 自定义）
 * @param lang 语言
 * @param labels 仓库级自定义标签（可选）
 * @returns 显示文本
 */
export function formatStatus(
  statusCode: string,
  lang: Language,
  labels?: Record<string, Record<string, string>>,
): string {
  if (labels?.[statusCode]?.[lang]) return labels[statusCode][lang]
  const locale = getLocale(lang)
  return locale.status[statusCode as StoryStatus] || statusCode
}

/**
 * 解析故事语言（从 config.json 中读取，默认 zh）
 * @param config 故事配置
 * @returns 语言代码
 */
export function resolveLang(config: { language?: string }): Language {
  return config.language === "en" ? "en" : "zh"
}
