name: Build & Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build README
        uses: yuelinghuashu/story-cli@v1
        with:
          command: "build"

      - name: Export EPUB
        uses: yuelinghuashu/story-cli@v1
        with:
          command: "epub --all"

      - name: Upload EPUB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: epub
          path: dist/epub/

      - name: Upload README
        uses: actions/upload-artifact@v4
        with:
          name: readme
          path: README.md